# Generated by Django 6.0.4 on 2026-04-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='budget',
            field=models.CharField(blank=True, max_length=255, verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='destination',
            name='how_to_get',
            field=models.TextField(blank=True, verbose_name='Как добраться'),
        ),
        migrations.AddField(
            model_name='destination',
            name='what_to_see',
            field=models.TextField(blank=True, verbose_name='Что посмотреть'),
        ),
    ]
