# Generated by Django 6.0.4 on 2026-04-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destination_budget_destination_how_to_get_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='days_count',
            field=models.CharField(blank=True, max_length=100, verbose_name='На сколько дней'),
        ),
        migrations.AddField(
            model_name='destination',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('train', 'Поезд'), ('car', 'Машина'), ('bus', 'Автобус'), ('plane', 'Самолет'), ('mixed', 'Несколько вариантов')], max_length=20, verbose_name='Лучший транспорт'),
        ),
    ]
