# Generated by Django 6.0.4 on 2026-04-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_destination_days_count_destination_transport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='gallery_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/gallery/', verbose_name='Галерея фото 1'),
        ),
        migrations.AddField(
            model_name='destination',
            name='gallery_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/gallery/', verbose_name='Галерея фото 2'),
        ),
        migrations.AddField(
            model_name='destination',
            name='gallery_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/gallery/', verbose_name='Галерея фото 3'),
        ),
        migrations.AddField(
            model_name='destination',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/heroes/', verbose_name='Hero фото'),
        ),
    ]
