# Generated by Django 6.0.4 on 2026-04-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_destination_gallery_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='gallery_image_1_caption',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подпись к фото 1'),
        ),
        migrations.AddField(
            model_name='destination',
            name='gallery_image_2_caption',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подпись к фото 2'),
        ),
        migrations.AddField(
            model_name='destination',
            name='gallery_image_3_caption',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подпись к фото 3'),
        ),
        migrations.AddField(
            model_name='destination',
            name='hero_image_caption',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подпись к Hero'),
        ),
    ]
