# Generated by Django 6.0.4 on 2026-05-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=2000, null=True)),
                ('user_agent_string', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('browser_family', models.CharField(blank=True, max_length=100, null=True)),
                ('os_family', models.CharField(blank=True, max_length=100, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['session_key', 'path'], name='analytics_p_session_4a2c86_idx')],
            },
        ),
    ]
