# Generated by Django 6.0.4 on 2026-04-18 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0004_destination_days_count_destination_transport_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название маршрута')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('content', models.TextField(blank=True, verbose_name='Полный текст')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='destinations.destination', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['title'],
            },
        ),
    ]
