# Generated by Django 6.0.4 on 2026-04-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ориентировочное время'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_includes',
            field=models.TextField(blank=True, verbose_name='Что входит в маршрут'),
        ),
        migrations.AddField(
            model_name='route',
            name='suitable_for',
            field=models.TextField(blank=True, verbose_name='Подходит кому'),
        ),
    ]
