# Generated by Django 6.0.4 on 2026-04-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_estimated_time_route_route_includes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='routes/', verbose_name='Фото маршрута 1'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_image_1_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись к фото маршрута 1'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='routes/', verbose_name='Фото маршрута 2'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_image_2_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись к фото маршрута 2'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='routes/', verbose_name='Фото маршрута 3'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_image_3_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись к фото маршрута 3'),
        ),
    ]
